Demo3
rogive/droneservice pull request #20
Opened 2020-09-23 05:17 UTC by rogive

Se agrega pasarela de pago, nuevas funcionalidades para el ingreso del perfil, nuevos componentes reutilizables, nuevos estilos en vistas. Los siguientes son los cambios generados:

src/Components/Certificates.css -> Se elimina style component en el archivo certificates y se crea un archivo .css
src/Components/Certificates.js -> Se incorpora el nuevo componente de buton tipo file "<FileButton>
src/Components/ClientSolicitudes.css -> Se elimina style component en el archivo ClientSolicitudes y se crea un archivo .css
src/Components/FileButton.js -> Se crea un nuevo componente para reemplazar el boton tipo file
src/Components/FileButton.css -> Se adiciona estilos al nuevo componente boton tipo file
src/Components/FlightLogs.js -> Se incorpora el nuevo componente de buton tipo file "<FileButton> y se transforma el componente de tipo clase a funcion.
src/Components/FlightLogs.js -> Se inhabilita temporalmente el upload de los documentos, mientras se le asigna el mvc en el backend, queda comentado temporalmente
src/Components/FlightLogsApp.js -> Se incorpora el nuevo componente de buton tipo file "<FileButton> y se transforma el componente de tipo clase a funcion.
src/Components/FlightLogsApp.js -> Se inhabilita temporalmente el upload de los documentos, mientras se le asigna el mvc en el backend, queda comentado temporalmente
src/Components/Header.css -> Se incorpora estilos en archivo .css al componente header y se retira los botones de mi perfil y cerrar sesion por nuevo elemento desplegable.
src/Components/LoginForm.js -> Se corrige la ruta de login del piloto en el axios
src/Components/NewModal.js -> Se crea nuevo modal de inicio de sesion
src/Components/NewModal.css -> Se agrega estilos al nuevo modal
src/Components/Others.js -> Se incorpora el nuevo componente de buton tipo file "<FileButton> y se transforma el componente de tipo clase a funcion.
src/Components/Others.js -> Se inhabilita temporalmente el upload de los documentos, mientras se le asigna el mvc en el backend, queda comentado temporalmente
src/Components/Payment.js -> Se incorpora el componente payment para la configuracion de la pasarela de pago
src/Components/PilotCard.js -> Se crea el componente PilotCard el cual es la carta de presentacion del piloto para mostrar mas detalle  del piloto en el explora del cliente
src/Components/PilotCard.css -> Se añade estilos a la carta de presentacion del piloto
src/Components/Portfolios.js -> Se incorpora el nuevo componente del boton tipo File
src/Components/Profile.js -> Eliminado, no se usaba este componente.
src/Components/Results.css -> Se adiciona estilos al componente Results.js
src/Components/Results.js -> Se incorpora el componente PilotCard, Para que sea mostrada la carta de presentacion del piloto cuando es clickeada alguna foto dentro de los resultados.
src/Components/Results.js -> Se incorpora el componente Payment, para pagar el contacto cuando es clickeado algun boton dentro de los resultados, si es exitoso mostrara el telefono del cliente
src/Components/SlideShow.js -> Nuevo carousel habilitado para ser usado en la pagina home (siguiente sprint).
src/Components/SlideShow.css -> Estilos y animación del carousel
src/Components/UpdateClientProfile.css -> Se cambia por UserProfrile
src/Components/UserForm.css -> Nuevos estilos al componente de registro de usuarios
src/Components/UserForm.js -> Se elimina style componente para fijar un archivo css, se renueva el formulario
src/Components/UpdateClientProfile.js → src/Components/UserProfile.js -> Se cambia el componente para que sea reutilizable tanto en el perfil cliente como en el perfil piloto
src/Components/UserProfile.css -> Se añade estilos al nuevo perfil de usuario
src/Pages/Footer.js -> Se crea un footer de la aplicacion con enlace al repositorio
src/Pages/Footer.css -> Se adiciona estilos
src/Pages/PaymentResponse.js -> Se agrega vista para el pago exitoso
src/Pages/PaymentResponse.css -> Se añade estilos a la viste de pago exitoso

2020-09-23 15:25 UTC, simonhoyos commented
Muchachos traten siempre que los PRs sean pequeños y especificos. PRs tan grandes son difíciles de leer y requieren mucho tiempo para revisarlos detalladamente. Esto hace que la probabilidad de que se nos pase un error aumente drasticamente

2020-09-23 15:29 UTC, rogive commented
> Muchachos traten siempre que los PRs sean pequeños y especificos. PRs tan grandes son difíciles de leer y requieren mucho tiempo para revisarlos detalladamente. Esto hace que la probabilidad de que se nos pase un error aumente drasticamente

SI, que pena Simon, nos ha pasado en las Demos y no debe ser así,  pero mejoraremos para no repetir esta mala practica.

2020-09-23 15:38 UTC, simonhoyos requested changes

2020-09-23 15:38 UTC, simonhoyos commented on .env
> +REACT_APP_EPAYCO_PUBLIC_KEY=a970413089c4b59136cdb63f778cb00a
Ojo con las variables de entorno. No se deben subir a git. Corran el comando `git rm --cached .env` para remover el archivo

2020-09-23 15:38 UTC, simonhoyos commented on src/Components/FlightLogs.js
> +/*  const uploadDocument = storage.ref(`Pilots/Pilot-${pilotId}/Certificates/` + name).put(selectedFile);
Borrar comentarios

2020-09-23 15:38 UTC, simonhoyos commented on src/Components/FlightLogs.js
> +     uploadDocument.on('state_changed',
Borrar comentarios

2020-09-23 15:38 UTC, simonhoyos commented on src/Components/FlightLogsApp.js
> +/*  const uploadDocument = storage.ref(`Pilots/Pilot-${pilotId}/Certificates/` + name).put(selectedFile);
Borrar comentarios

2020-09-23 15:38 UTC, simonhoyos commented on src/Components/FlightLogsApp.js
> +     uploadDocument.on('state_changed',
Borrar todos los comentarios en general

2020-09-23 15:38 UTC, simonhoyos commented on src/Components/Header.js
> +          // <div>
Los comentarios son código muerto. Si no se va a utilizar es mejor no tenerlos

2020-09-23 15:38 UTC, simonhoyos commented on src/Components/Payment.js
> +        console.log(data.data.x_cod_response)
Borrar los console.logs

2020-09-24 14:29 UTC, simonhoyos approved these changes

2020-09-24 14:36 UTC, merged