explora logic update
rogive/droneservice pull request #9
Opened 2020-08-29 01:33 UTC by jpalacio0612

### Se actualizó la lógica de la vista explora en el componente Results.js, tal y como se había hablado en nuestro sprint planning. Ahora solo se envían los tags de filtro al backend, este realiza el filtrado y regresa la información solo de los pilotos filtrados.

2020-08-31 10:34 UTC, simonhoyos requested changes

2020-08-31 10:34 UTC, simonhoyos commented on src/Components/Results.js
> +        const result = await axios.post('http://localhost:8000/pilotos/filtrar',{info})
Está petición va a crear algún recurso en el lado del servidor? si no va a crear ningún registro, sino que estamos obteniendo información es mejor dejarlo como un get

2020-08-31 15:11 UTC, jpalacio0612 commented on src/Components/Results.js
> +        const result = await axios.post('http://localhost:8000/pilotos/filtrar',{info})
No crea ningún recurso solo trae información, ya se cambio por get.

2020-09-01 10:07 UTC, simonhoyos approved these changes

2020-09-01 12:34 UTC, merged